title: Think Build Value - Top business knowledge in one place
description: >-
  ðŸ’¡Think ðŸ”¨Build ðŸ’°Value is a resource of all curated knowledge from top businessmen and entrepreneurs in the world.
  From business creation to product delivery. We
  create short posts to get you going on your journey.
lang: en-US
image: assets/img/ogp.png
mode: light
author:
  name: Think Build Value by Valentinas
  bio: >-
    ðŸ’¡Think ðŸ”¨Build ðŸ’°Value is a resource of all curated knowledge from top businessmen and entrepreneurs in the world.
  username: Valentinas  
  #github: github_username
  #twitter: 15165
  #facebook: facebook_username
  #email: your-email@email.com
  avatar: /assets/img/logo.png
url: 'https://thinkbuildvalue.com'
baseurl: null
permalink: '/:title/'
google_analytics: null
fb_appid: null
collections:
  posts:
    output: true
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
defaults:
  - scope:
      path: ''
    values:
      layout: post
      comments: false
jekyll_compose:
  post_default_front_matter:
    modified: null
    tags: []
    description: null
  draft_default_front_matter:
    modified: null
    tags: []
    description: null
number_of_posts: 5
sass:
  style: compressed
include:
  - _redirects
  - .htaccess
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
